//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoLibraryApp
{
    partial class CassetteDetailForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.pnlMain = new System.Windows.Forms.Panel();
            this.btnClose = new System.Windows.Forms.Button();
            this.txtDescription = new System.Windows.Forms.TextBox();
            this.lblDescription = new System.Windows.Forms.Label();
            this.lblGenreVal = new System.Windows.Forms.Label();
            this.lblGenre = new System.Windows.Forms.Label();
            this.lblYearVal = new System.Windows.Forms.Label();
            this.lblYear = new System.Windows.Forms.Label();
            this.lblDirectorVal = new System.Windows.Forms.Label();
            this.lblDirector = new System.Windows.Forms.Label();
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblNoImage = new System.Windows.Forms.Label();
            this.picPoster = new System.Windows.Forms.PictureBox();
            this.pnlMain.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picPoster)).BeginInit();
            this.SuspendLayout();
            //
            // pnlMain
            //
            this.pnlMain.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(30)))), ((int)(((byte)(48)))));
            this.pnlMain.Controls.Add(this.btnClose);
            this.pnlMain.Controls.Add(this.txtDescription);
            this.pnlMain.Controls.Add(this.lblDescription);
            this.pnlMain.Controls.Add(this.lblGenreVal);
            this.pnlMain.Controls.Add(this.lblGenre);
            this.pnlMain.Controls.Add(this.lblYearVal);
            this.pnlMain.Controls.Add(this.lblYear);
            this.pnlMain.Controls.Add(this.lblDirectorVal);
            this.pnlMain.Controls.Add(this.lblDirector);
            this.pnlMain.Controls.Add(this.lblTitle);
            this.pnlMain.Controls.Add(this.lblNoImage);
            this.pnlMain.Controls.Add(this.picPoster);
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(0, 0);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Padding = new System.Windows.Forms.Padding(20);
            this.pnlMain.Size = new System.Drawing.Size(520, 420);
            this.pnlMain.TabIndex = 0;
            //
            // picPoster
            //
            this.picPoster.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(50)))), ((int)(((byte)(70)))));
            this.picPoster.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.picPoster.Location = new System.Drawing.Point(25, 60);
            this.picPoster.Name = "picPoster";
            this.picPoster.Size = new System.Drawing.Size(140, 200);
            this.picPoster.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picPoster.TabIndex = 0;
            this.picPoster.TabStop = false;
            //
            // lblNoImage
            //
            this.lblNoImage.AutoSize = true;
            this.lblNoImage.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(130)))), ((int)(((byte)(150)))));
            this.lblNoImage.Location = new System.Drawing.Point(35, 130);
            this.lblNoImage.Name = "lblNoImage";
            this.lblNoImage.Size = new System.Drawing.Size(120, 15);
            this.lblNoImage.TabIndex = 1;
            this.lblNoImage.Text = "Няма налична снимка";
            this.lblNoImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            //
            // lblTitle
            //
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(200)))), ((int)(((byte)(100)))));
            this.lblTitle.Location = new System.Drawing.Point(185, 25);
            this.lblTitle.MaximumSize = new System.Drawing.Size(310, 0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(45, 25);
            this.lblTitle.TabIndex = 2;
            this.lblTitle.Text = "Title";
            //
            // lblDirector
            //
            this.lblDirector.AutoSize = true;
            this.lblDirector.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(180)))), ((int)(((byte)(200)))));
            this.lblDirector.Location = new System.Drawing.Point(185, 65);
            this.lblDirector.Name = "lblDirector";
            this.lblDirector.Size = new System.Drawing.Size(58, 15);
            this.lblDirector.TabIndex = 3;
            this.lblDirector.Text = "Режисьор";
            //
            // lblDirectorVal
            //
            this.lblDirectorVal.AutoSize = true;
            this.lblDirectorVal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(235)))));
            this.lblDirectorVal.Location = new System.Drawing.Point(185, 82);
            this.lblDirectorVal.Name = "lblDirectorVal";
            this.lblDirectorVal.Size = new System.Drawing.Size(12, 15);
            this.lblDirectorVal.TabIndex = 4;
            this.lblDirectorVal.Text = "-";
            //
            // lblYear
            //
            this.lblYear.AutoSize = true;
            this.lblYear.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(180)))), ((int)(((byte)(200)))));
            this.lblYear.Location = new System.Drawing.Point(185, 110);
            this.lblYear.Name = "lblYear";
            this.lblYear.Size = new System.Drawing.Size(43, 15);
            this.lblYear.TabIndex = 5;
            this.lblYear.Text = "Година";
            //
            // lblYearVal
            //
            this.lblYearVal.AutoSize = true;
            this.lblYearVal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(235)))));
            this.lblYearVal.Location = new System.Drawing.Point(185, 127);
            this.lblYearVal.Name = "lblYearVal";
            this.lblYearVal.Size = new System.Drawing.Size(12, 15);
            this.lblYearVal.TabIndex = 6;
            this.lblYearVal.Text = "-";
            //
            // lblGenre
            //
            this.lblGenre.AutoSize = true;
            this.lblGenre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(180)))), ((int)(((byte)(200)))));
            this.lblGenre.Location = new System.Drawing.Point(185, 155);
            this.lblGenre.Name = "lblGenre";
            this.lblGenre.Size = new System.Drawing.Size(35, 15);
            this.lblGenre.TabIndex = 7;
            this.lblGenre.Text = "Жанр";
            //
            // lblGenreVal
            //
            this.lblGenreVal.AutoSize = true;
            this.lblGenreVal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(235)))));
            this.lblGenreVal.Location = new System.Drawing.Point(185, 172);
            this.lblGenreVal.Name = "lblGenreVal";
            this.lblGenreVal.Size = new System.Drawing.Size(12, 15);
            this.lblGenreVal.TabIndex = 8;
            this.lblGenreVal.Text = "-";
            //
            // lblDescription
            //
            this.lblDescription.AutoSize = true;
            this.lblDescription.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(180)))), ((int)(((byte)(200)))));
            this.lblDescription.Location = new System.Drawing.Point(185, 205);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Size = new System.Drawing.Size(62, 15);
            this.lblDescription.TabIndex = 9;
            this.lblDescription.Text = "Описание";
            //
            // txtDescription
            //
            this.txtDescription.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(50)))), ((int)(((byte)(70)))));
            this.txtDescription.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtDescription.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtDescription.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(235)))));
            this.txtDescription.Location = new System.Drawing.Point(185, 225);
            this.txtDescription.Multiline = true;
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.ReadOnly = true;
            this.txtDescription.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtDescription.Size = new System.Drawing.Size(310, 120);
            this.txtDescription.TabIndex = 10;
            //
            // btnClose
            //
            this.btnClose.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(200)))), ((int)(((byte)(100)))));
            this.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnClose.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(22)))), ((int)(((byte)(36)))));
            this.btnClose.Location = new System.Drawing.Point(390, 360);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(105, 40);
            this.btnClose.TabIndex = 11;
            this.btnClose.Text = "Затвори";
            this.btnClose.UseVisualStyleBackColor = false;
            this.btnClose.Click += new System.EventHandler(this.BtnClose_Click);
            //
            // CassetteDetailForm
            //
            this.AcceptButton = this.btnClose;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(26)))), ((int)(((byte)(42)))));
            this.ClientSize = new System.Drawing.Size(520, 420);
            this.Controls.Add(this.pnlMain);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "CassetteDetailForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Детайли за касета";
            this.pnlMain.ResumeLayout(false);
            this.pnlMain.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picPoster)).EndInit();
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.Panel pnlMain;
        private System.Windows.Forms.PictureBox picPoster;
        private System.Windows.Forms.Label lblNoImage;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblDirector;
        private System.Windows.Forms.Label lblDirectorVal;
        private System.Windows.Forms.Label lblYear;
        private System.Windows.Forms.Label lblYearVal;
        private System.Windows.Forms.Label lblGenre;
        private System.Windows.Forms.Label lblGenreVal;
        private System.Windows.Forms.Label lblDescription;
        private System.Windows.Forms.TextBox txtDescription;
        private System.Windows.Forms.Button btnClose;
    }
}
